const Studenti = [
  {
    "StudentId": 13,
    "Ime": "JELENA",
    "Prezime": "AVRAMOVIĆ  ",
    "DatumRodjenja": "1.1.2003",
    "BrojIndeksa": "2u1/0072/22  ",
    "Telefon": "3,8162E+11",
    "Email": "jelena.avramovic@gmail.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 23,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 14,
    "Ime": "MIROSLAVA",
    "Prezime": "JOVANOVIĆ  ",
    "DatumRodjenja": "1.1.2001",
    "BrojIndeksa": "2p1/0129/23  ",
    "Telefon": "3,81621E+11",
    "Email": "miroslava.jovanovic@hotmail.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 39,
    "PTT": 11460,
    "Grad": "Barajevo",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 15,
    "Ime": "NOVA",
    "Prezime": "RISTIĆ  ",
    "DatumRodjenja": "1.1.2004",
    "BrojIndeksa": "1m1/0051/24  ",
    "Telefon": "3,81633E+11",
    "Email": "nova.ristic@gmail.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 43,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 16,
    "Ime": "VESELINKA",
    "Prezime": "MILUNOVIĆ",
    "DatumRodjenja": "1.1.2005",
    "BrojIndeksa": "1e1/0045/23  ",
    "Telefon": "3,81648E+11",
    "Email": "veselinka.milunovic@yahoo.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 1,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 17,
    "Ime": "GORDANA",
    "Prezime": "KOSANOVIĆ  ",
    "DatumRodjenja": "1.1.2002",
    "BrojIndeksa": "2e1/0096/22  ",
    "Telefon": "3,81659E+11",
    "Email": "gordana.kosanovic@gmail.com  ",
    "Ulica": "RUZVELTOVA",
    "BrojKuce": 46,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 18,
    "Ime": "PETAR",
    "Prezime": "PFANDLER  ",
    "DatumRodjenja": "1.1.2002",
    "BrojIndeksa": "1i1/0187/24  ",
    "Telefon": "3,81604E+11",
    "Email": "petar.pfandler@yahoo.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 7,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 19,
    "Ime": "JELENA",
    "Prezime": "PURIĆ  ",
    "DatumRodjenja": "1.2.2005",
    "BrojIndeksa": "1m1/0003/23  ",
    "Telefon": "3,81616E+11",
    "Email": "jelena.puric@gmail.com  ",
    "Ulica": "SLAVUJEV VENAC",
    "BrojKuce": 36,
    "PTT": 11306,
    "Grad": "Grocka",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 20,
    "Ime": "RADMILA",
    "Prezime": "GRINVALD  ",
    "DatumRodjenja": "1.2.2003",
    "BrojIndeksa": "2p1/0200/24  ",
    "Telefon": "3,81629E+11",
    "Email": "radmila.grinvald@hotmail.com  ",
    "Ulica": "RUZVELTOVA",
    "BrojKuce": 38,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 21,
    "Ime": "VJERA",
    "Prezime": "DELIĆ  ",
    "DatumRodjenja": "1.2.2005",
    "BrojIndeksa": "1i1/0011/22  ",
    "Telefon": "3,81631E+11",
    "Email": "vjera.delic@yahoo.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 14,
    "PTT": 11060,
    "Grad": "Palilula",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 22,
    "Ime": "PAVLINA",
    "Prezime": "JANJIĆ  ",
    "DatumRodjenja": "1.2.2004",
    "BrojIndeksa": "2e1/0088/24  ",
    "Telefon": "3,81647E+11",
    "Email": "pavlina.janjic@gmail.com  ",
    "Ulica": "TOPLIČKA",
    "BrojKuce": 8,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 23,
    "Ime": "BRANISLAV",
    "Prezime": "VRANEŠ  ",
    "DatumRodjenja": "1.2.2002",
    "BrojIndeksa": "2i1/0110/23  ",
    "Telefon": "3,81658E+11",
    "Email": "branislav.vranes@hotmail.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 4,
    "PTT": 11460,
    "Grad": "Barajevo",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 24,
    "Ime": "SINIŠA",
    "Prezime": "MIKETIĆ  ",
    "DatumRodjenja": "1.2.2002",
    "BrojIndeksa": "1u1/0054/22  ",
    "Telefon": "3,81604E+11",
    "Email": "sinisa.miketic@gmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 22,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 1
  },
  {
    "StudentId": 25,
    "Ime": "TANJA",
    "Prezime": "TASIĆ  ",
    "DatumRodjenja": "1.2.2005",
    "BrojIndeksa": "2m1/0022/23  ",
    "Telefon": "3,81617E+11",
    "Email": "tanja.tasic@yahoo.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 6,
    "PTT": 11000,
    "Grad": "Vračar",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 26,
    "Ime": "DANICA",
    "Prezime": "MIJATOVIĆ  ",
    "DatumRodjenja": "1.2.2001",
    "BrojIndeksa": "1p1/0069/24  ",
    "Telefon": "3,8163E+11",
    "Email": "danica.mijatovic@gmail.com  ",
    "Ulica": "KOSTE TAUŠANOVIĆA",
    "BrojKuce": 8,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 27,
    "Ime": "TIJANA",
    "Prezime": "DUDUKOVIĆ  ",
    "DatumRodjenja": "1.3.2001",
    "BrojIndeksa": "2e1/0191/22  ",
    "Telefon": "3,81632E+11",
    "Email": "tijana.dudukovic@hotmail.com  ",
    "Ulica": "SLAVUJEV VENAC",
    "BrojKuce": 11,
    "PTT": 11070,
    "Grad": "Novi Beograd",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 28,
    "Ime": "JELICA",
    "Prezime": "SRBINOVSKA  ",
    "DatumRodjenja": "1.3.2003",
    "BrojIndeksa": "1i1/0002/23  ",
    "Telefon": "3,81641E+11",
    "Email": "jelica.srbinovska@yahoo.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 43,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 29,
    "Ime": "NURI",
    "Prezime": "ŠULUBURIĆ  ",
    "DatumRodjenja": "1.3.2001",
    "BrojIndeksa": "2u1/0107/24  ",
    "Telefon": "3,81659E+11",
    "Email": "nuri.suluburic@gmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 28,
    "PTT": 11070,
    "Grad": "Novi Beograd",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 1
  },
  {
    "StudentId": 30,
    "Ime": "MILOMIR",
    "Prezime": "STANIŠIĆ  ",
    "DatumRodjenja": "1.3.2002",
    "BrojIndeksa": "2p1/0176/23  ",
    "Telefon": "3,81605E+11",
    "Email": "milomir.stanisic@hotmail.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 23,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 31,
    "Ime": "MILANKO",
    "Prezime": "BABIĆ  ",
    "DatumRodjenja": "1.3.2005",
    "BrojIndeksa": "1e1/0094/22  ",
    "Telefon": "3,81614E+11",
    "Email": "milanko.babic@yahoo.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 39,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 1
  },
  {
    "StudentId": 32,
    "Ime": "MARKO",
    "Prezime": "GAVROVSKI  ",
    "DatumRodjenja": "1.3.2003",
    "BrojIndeksa": "2m1/0121/24  ",
    "Telefon": "3,81627E+11",
    "Email": "marko.gavrovski@gmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 23,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 1
  },
  {
    "StudentId": 33,
    "Ime": "SVETLANA",
    "Prezime": "VEŠOVIĆ  ",
    "DatumRodjenja": "1.3.2002",
    "BrojIndeksa": "1i1/0198/23  ",
    "Telefon": "3,8164E+11",
    "Email": "svetlana.vesovic@hotmail.com  ",
    "Ulica": "TOPLIČKA",
    "BrojKuce": 16,
    "PTT": 11460,
    "Grad": "Barajevo",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 34,
    "Ime": "DUŠKO",
    "Prezime": "MARINKOVIĆ  ",
    "DatumRodjenja": "1.3.2001",
    "BrojIndeksa": "1p1/0040/22  ",
    "Telefon": "3,81644E+11",
    "Email": "dusko.marinkovic@yahoo.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 25,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 35,
    "Ime": "IRENA",
    "Prezime": "GRČIĆ  ",
    "DatumRodjenja": "1.3.2003",
    "BrojIndeksa": "2e1/0116/23  ",
    "Telefon": "3,81656E+11",
    "Email": "irena.grcic@gmail.com  ",
    "Ulica": "TOPLIČKA",
    "BrojKuce": 18,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 36,
    "Ime": "VIOLETA",
    "Prezime": "ILIĆ  ",
    "DatumRodjenja": "1.3.2003",
    "BrojIndeksa": "2u1/0169/24  ",
    "Telefon": "3,81607E+11",
    "Email": "violeta.ilic@hotmail.com  ",
    "Ulica": "STJEPANA LJUBIŠE",
    "BrojKuce": 19,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 37,
    "Ime": "MARINA",
    "Prezime": "LAKIĆ  ",
    "DatumRodjenja": "1.3.2001",
    "BrojIndeksa": "1m1/0019/23  ",
    "Telefon": "3,81616E+11",
    "Email": "marina.lakic@gmail.com  ",
    "Ulica": "KOSTE TAUŠANOVIĆA",
    "BrojKuce": 9,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 38,
    "Ime": "JELICA",
    "Prezime": "JEVTIĆ  ",
    "DatumRodjenja": "1.4.2002",
    "BrojIndeksa": "1i1/0145/24  ",
    "Telefon": "3,81629E+11",
    "Email": "jelica.jevtic@yahoo.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 42,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 39,
    "Ime": "DEJAN",
    "Prezime": "BULAJIĆ  ",
    "DatumRodjenja": "1.4.2005",
    "BrojIndeksa": "2p1/0038/22  ",
    "Telefon": "3,81636E+11",
    "Email": "dejan.bulajic@gmail.com  ",
    "Ulica": "STJEPANA LJUBIŠE",
    "BrojKuce": 5,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 40,
    "Ime": "IVAN",
    "Prezime": "ČONIĆ  ",
    "DatumRodjenja": "1.4.2002",
    "BrojIndeksa": "2e1/0066/23  ",
    "Telefon": "3,81642E+11",
    "Email": "ivan.conic@hotmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 32,
    "PTT": 11306,
    "Grad": "Grocka",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 1
  },
  {
    "StudentId": 41,
    "Ime": "DRAGANA",
    "Prezime": "ĐORĐEVIĆ  ",
    "DatumRodjenja": "1.4.2004",
    "BrojIndeksa": "2m1/0055/24  ",
    "Telefon": "3,81658E+11",
    "Email": "dragana.djordjevic@gmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 32,
    "PTT": 11460,
    "Grad": "Barajevo",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 42,
    "Ime": "ŽIVADINKA",
    "Prezime": "ĐORĐEVIĆ  ",
    "DatumRodjenja": "1.5.2001",
    "BrojIndeksa": "1u1/0172/23  ",
    "Telefon": "3,81609E+11",
    "Email": "zivadinka.djordjevic@yahoo.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 19,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 43,
    "Ime": "SLOBODAN",
    "Prezime": "CVETKOVIĆ  ",
    "DatumRodjenja": "1.5.2005",
    "BrojIndeksa": "1i1/0007/22  ",
    "Telefon": "3,81617E+11",
    "Email": "slobodan.cvetkovic@gmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 6,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 44,
    "Ime": "ZORAN",
    "Prezime": "PAŠARA  ",
    "DatumRodjenja": "1.6.2004",
    "BrojIndeksa": "2p1/0137/24  ",
    "Telefon": "3,81627E+11",
    "Email": "zoran.pasara@hotmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 45,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 46,
    "Ime": "NADA",
    "Prezime": "VASIĆ  ",
    "DatumRodjenja": "1.6.2001",
    "BrojIndeksa": "2m1/0193/22  ",
    "Telefon": "3,81642E+11",
    "Email": "nada.vasic@gmail.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 49,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 47,
    "Ime": "SNEŽANA",
    "Prezime": "MIŠIĆ  ",
    "DatumRodjenja": "1.6.2005",
    "BrojIndeksa": "2u1/0182/24  ",
    "Telefon": "3,81652E+11",
    "Email": "snezana.misic@hotmail.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 5,
    "PTT": 11060,
    "Grad": "Palilula",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 48,
    "Ime": "LJILJANA",
    "Prezime": "SMILJANIĆ  ",
    "DatumRodjenja": "1.6.2003",
    "BrojIndeksa": "1p1/0100/23  ",
    "Telefon": "3,81604E+11",
    "Email": "ljiljana.smiljanic@gmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 9,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 49,
    "Ime": "GORDANA",
    "Prezime": "BRAJOVIĆ  ",
    "DatumRodjenja": "1.6.2003",
    "BrojIndeksa": "2i1/0064/24  ",
    "Telefon": "3,81611E+11",
    "Email": "gordana.brajovic@yahoo.com  ",
    "Ulica": "SLAVUJEV VENAC",
    "BrojKuce": 11,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 50,
    "Ime": "DRAGA",
    "Prezime": "GAGIĆ  ",
    "DatumRodjenja": "1.7.2005",
    "BrojIndeksa": "1e1/0135/23  ",
    "Telefon": "3,81629E+11",
    "Email": "draga.gagic@gmail.com  ",
    "Ulica": "STJEPANA LJUBIŠE",
    "BrojKuce": 10,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 51,
    "Ime": "NEVENKA",
    "Prezime": "VUKMANOVIĆ  ",
    "DatumRodjenja": "1.7.2005",
    "BrojIndeksa": "2m1/0157/22  ",
    "Telefon": "3,81637E+11",
    "Email": "nevenka.vukmanovic@hotmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 10,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 52,
    "Ime": "IVONA",
    "Prezime": "MILIĆ  ",
    "DatumRodjenja": "1.7.2004",
    "BrojIndeksa": "1i1/0033/24  ",
    "Telefon": "3,81649E+11",
    "Email": "ivona.milic@gmail.com  ",
    "Ulica": "STJEPANA LJUBIŠE",
    "BrojKuce": 13,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 53,
    "Ime": "SNEŽANA",
    "Prezime": "CRVENČANIN  ",
    "DatumRodjenja": "1.7.2005",
    "BrojIndeksa": "1u1/0014/23  ",
    "Telefon": "3,81653E+11",
    "Email": "snezana.crvencanin@yahoo.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 6,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 54,
    "Ime": "LJILJANA",
    "Prezime": "RAFAJLOVIĆ  ",
    "DatumRodjenja": "1.7.2005",
    "BrojIndeksa": "2e1/0179/24  ",
    "Telefon": "3,81605E+11",
    "Email": "ljiljana.rafajlovic@gmail.com  ",
    "Ulica": "KOSTE TAUŠANOVIĆA",
    "BrojKuce": 6,
    "PTT": 11060,
    "Grad": "Palilula",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 55,
    "Ime": "MILICA",
    "Prezime": "RAFTOVIĆ LOŠTREK  ",
    "DatumRodjenja": "1.7.2001",
    "BrojIndeksa": "2p1/0090/22  ",
    "Telefon": "3,81618E+11",
    "Email": "milica.raftoviclostrek@hotmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 8,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 56,
    "Ime": "LJILJANA",
    "Prezime": "PROKIĆ MANOJLOVIĆ  ",
    "DatumRodjenja": "1.8.2005",
    "BrojIndeksa": "1m1/0081/23  ",
    "Telefon": "3,81627E+11",
    "Email": "ljiljana.prokicmanojlovic@gmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 14,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 57,
    "Ime": "ĐELADIN",
    "Prezime": "ALIMPIĆ  ",
    "DatumRodjenja": "1.8.2005",
    "BrojIndeksa": "2u1/0118/24  ",
    "Telefon": "3,81633E+11",
    "Email": "djeladin.alimpic@yahoo.com  ",
    "Ulica": "SLAVUJEV VENAC",
    "BrojKuce": 31,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 1
  },
  {
    "StudentId": 58,
    "Ime": "GORDANA",
    "Prezime": "PEROVIĆ  ",
    "DatumRodjenja": "1.8.2004",
    "BrojIndeksa": "2e1/0060/23  ",
    "Telefon": "3,81648E+11",
    "Email": "gordana.perovic@gmail.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 39,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 59,
    "Ime": "MIRJANA",
    "Prezime": "IVANOVIĆ  ",
    "DatumRodjenja": "1.8.2004",
    "BrojIndeksa": "1i1/0050/24  ",
    "Telefon": "3,81653E+11",
    "Email": "mirjana.ivanovic@hotmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 32,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 60,
    "Ime": "MARIJA",
    "Prezime": "DIMITRIJEVIĆ  ",
    "DatumRodjenja": "1.8.2001",
    "BrojIndeksa": "1p1/0146/22  ",
    "Telefon": "3,81607E+11",
    "Email": "marija.dimitrijevic@yahoo.com  ",
    "Ulica": "KOSTE TAUŠANOVIĆA",
    "BrojKuce": 10,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 61,
    "Ime": "SRĐAN",
    "Prezime": "KLANČNIK  ",
    "DatumRodjenja": "1.8.2005",
    "BrojIndeksa": "2m1/0190/23  ",
    "Telefon": "3,81619E+11",
    "Email": "srdjan.klancnik@gmail.com  ",
    "Ulica": "STJEPANA LJUBIŠE",
    "BrojKuce": 33,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 1
  },
  {
    "StudentId": 62,
    "Ime": "ĐORĐE",
    "Prezime": "VASILJEV  ",
    "DatumRodjenja": "1.8.2004",
    "BrojIndeksa": "1u1/0125/24  ",
    "Telefon": "3,81622E+11",
    "Email": "djordje.vasiljev@yahoo.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 48,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 1
  },
  {
    "StudentId": 63,
    "Ime": "ŽARKO",
    "Prezime": "JOVIĆEVIĆ  ",
    "DatumRodjenja": "1.8.2003",
    "BrojIndeksa": "1e1/0080/22  ",
    "Telefon": "3,81636E+11",
    "Email": "zarko.jovicevic@gmail.com  ",
    "Ulica": "KOSTE TAUŠANOVIĆA",
    "BrojKuce": 3,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 1
  },
  {
    "StudentId": 64,
    "Ime": "ZORAN",
    "Prezime": "VASIĆ  ",
    "DatumRodjenja": "1.8.2005",
    "BrojIndeksa": "2p1/0031/23  ",
    "Telefon": "3,81644E+11",
    "Email": "zoran.vasic@hotmail.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 8,
    "PTT": 11306,
    "Grad": "Grocka",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 65,
    "Ime": "ALEKSANDRA",
    "Prezime": "NINAJ  ",
    "DatumRodjenja": "1.8.2003",
    "BrojIndeksa": "1m1/0177/24  ",
    "Telefon": "3,81656E+11",
    "Email": "aleksandra.ninaj@yahoo.com  ",
    "Ulica": "SVETOG NIKOLE",
    "BrojKuce": 60,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 66,
    "Ime": "DANIJEL",
    "Prezime": "RISTIĆ  ",
    "DatumRodjenja": "1.8.2003",
    "BrojIndeksa": "2i1/0166/22  ",
    "Telefon": "3,81608E+11",
    "Email": "danijel.ristic@gmail.com  ",
    "Ulica": "SLAVUJEV VENAC",
    "BrojKuce": 22,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 67,
    "Ime": "TAMARA",
    "Prezime": "STANKOVIĆ  ",
    "DatumRodjenja": "1.8.2004",
    "BrojIndeksa": "2e1/0122/23  ",
    "Telefon": "3,81613E+11",
    "Email": "tamara.stankovic@hotmail.com  ",
    "Ulica": "RUZVELTOVA",
    "BrojKuce": 46,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 68,
    "Ime": "ANJA",
    "Prezime": "JOVANOVIĆ  ",
    "DatumRodjenja": "1.8.2003",
    "BrojIndeksa": "2u1/0020/24  ",
    "Telefon": "3,81622E+11",
    "Email": "anja.jovanovic@yahoo.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 11,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 69,
    "Ime": "IVAN",
    "Prezime": "MILJKOVIĆ  ",
    "DatumRodjenja": "1.8.2002",
    "BrojIndeksa": "1p1/0153/23  ",
    "Telefon": "3,81637E+11",
    "Email": "ivan.miljkovic@gmail.com  ",
    "Ulica": "SVETOG NIKOLE",
    "BrojKuce": 46,
    "PTT": 11460,
    "Grad": "Barajevo",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 70,
    "Ime": "LJILJANA",
    "Prezime": "ADAMOVIĆ  ",
    "DatumRodjenja": "1.9.2004",
    "BrojIndeksa": "1e1/0113/24  ",
    "Telefon": "3,81646E+11",
    "Email": "ljiljana.adamovic@hotmail.com  ",
    "Ulica": "STJEPANA LJUBIŠE",
    "BrojKuce": 23,
    "PTT": 11306,
    "Grad": "Grocka",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 71,
    "Ime": "BRANKO",
    "Prezime": "BILA  ",
    "DatumRodjenja": "1.9.2003",
    "BrojIndeksa": "1i1/0079/22  ",
    "Telefon": "3,81655E+11",
    "Email": "branko.bila@gmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 40,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 72,
    "Ime": "DRAGIŠA",
    "Prezime": "JELIĆ  ",
    "DatumRodjenja": "1.9.2005",
    "BrojIndeksa": "2m1/0062/23  ",
    "Telefon": "3,81607E+11",
    "Email": "dragisa.jelic@yahoo.com  ",
    "Ulica": "SVETOG NIKOLE",
    "BrojKuce": 22,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 1
  },
  {
    "StudentId": 73,
    "Ime": "JASMINA",
    "Prezime": "PETRONIJEVIĆ  ",
    "DatumRodjenja": "1.9.2003",
    "BrojIndeksa": "1u1/0101/24  ",
    "Telefon": "3,81612E+11",
    "Email": "jasmina.petronijevic@hotmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 5,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 74,
    "Ime": "SLOBODAN",
    "Prezime": "RADOJKOVIĆ  ",
    "DatumRodjenja": "1.10.2004",
    "BrojIndeksa": "2e1/0009/22  ",
    "Telefon": "3,81626E+11",
    "Email": "slobodan.radojkovic@gmail.com  ",
    "Ulica": "TOPLIČKA",
    "BrojKuce": 8,
    "PTT": 11306,
    "Grad": "Grocka",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 1
  },
  {
    "StudentId": 75,
    "Ime": "PETAR",
    "Prezime": "STANIĆ  ",
    "DatumRodjenja": "1.10.2004",
    "BrojIndeksa": "2p1/0185/23  ",
    "Telefon": "3,81639E+11",
    "Email": "petar.stanic@yahoo.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 5,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 76,
    "Ime": "MARINA",
    "Prezime": "MIKETIĆ  ",
    "DatumRodjenja": "1.10.2004",
    "BrojIndeksa": "1m1/0162/24  ",
    "Telefon": "3,81646E+11",
    "Email": "marina.miketic@gmail.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 39,
    "PTT": 11070,
    "Grad": "Novi Beograd",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 77,
    "Ime": "PREDRAG",
    "Prezime": "DRAGIĆ  ",
    "DatumRodjenja": "1.10.2001",
    "BrojIndeksa": "1i1/0159/23  ",
    "Telefon": "3,81652E+11",
    "Email": "predrag.dragic@hotmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 1,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 79,
    "Ime": "NIKOLA",
    "Prezime": "COJIĆ  ",
    "DatumRodjenja": "1.10.2002",
    "BrojIndeksa": "2e1/0057/24  ",
    "Telefon": "3,81616E+11",
    "Email": "nikola.cojic@gmail.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 1,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 1
  },
  {
    "StudentId": 80,
    "Ime": "MINA",
    "Prezime": "STEFANOVIĆ  ",
    "DatumRodjenja": "1.10.2002",
    "BrojIndeksa": "1p1/0194/23  ",
    "Telefon": "3,81628E+11",
    "Email": "mina.stefanovic@hotmail.com  ",
    "Ulica": "SVETOG NIKOLE",
    "BrojKuce": 20,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 81,
    "Ime": "NEVENKA",
    "Prezime": "GAJIĆ  ",
    "DatumRodjenja": "1.11.2003",
    "BrojIndeksa": "1u1/0165/22  ",
    "Telefon": "3,81632E+11",
    "Email": "nevenka.gajic@gmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 44,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 82,
    "Ime": "MILAN",
    "Prezime": "TUOVIĆ  ",
    "DatumRodjenja": "1.11.2004",
    "BrojIndeksa": "2i1/0131/24  ",
    "Telefon": "3,81643E+11",
    "Email": "milan.tuovic@yahoo.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 31,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 83,
    "Ime": "SONJA",
    "Prezime": "ĐORĐEVIĆ  ",
    "DatumRodjenja": "1.11.2002",
    "BrojIndeksa": "1e1/0075/23  ",
    "Telefon": "3,81658E+11",
    "Email": "sonja.djordjevic@gmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 30,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 84,
    "Ime": "SILVIJA",
    "Prezime": "MIJAILOVIĆ  ",
    "DatumRodjenja": "1.11.2003",
    "BrojIndeksa": "2m1/0048/22  ",
    "Telefon": "3,81601E+11",
    "Email": "silvija.mijailovic@yahoo.com  ",
    "Ulica": "SVETOG NIKOLE",
    "BrojKuce": 20,
    "PTT": 11306,
    "Grad": "Grocka",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 85,
    "Ime": "ANĐELKO",
    "Prezime": "PETROVIĆ  ",
    "DatumRodjenja": "1.11.2004",
    "BrojIndeksa": "1i1/0006/24  ",
    "Telefon": "3,81616E+11",
    "Email": "andjelko.petrovic@gmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 25,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 86,
    "Ime": "DUNJA",
    "Prezime": "STOJILJKOVIĆ  ",
    "DatumRodjenja": "1.11.2005",
    "BrojIndeksa": "2u1/0183/23  ",
    "Telefon": "3,81625E+11",
    "Email": "dunja.stojiljkovic@hotmail.com  ",
    "Ulica": "KOSTE TAUŠANOVIĆA",
    "BrojKuce": 6,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 87,
    "Ime": "GORDANA",
    "Prezime": "EMINOVIĆ  ",
    "DatumRodjenja": "1.12.2002",
    "BrojIndeksa": "1p1/0109/22  ",
    "Telefon": "3,81636E+11",
    "Email": "gordana.eminovic@yahoo.com  ",
    "Ulica": "IGMANSKA",
    "BrojKuce": 16,
    "PTT": 11460,
    "Grad": "Barajevo",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 88,
    "Ime": "JASMINA",
    "Prezime": "MATIĆ  ",
    "DatumRodjenja": "1.12.2004",
    "BrojIndeksa": "2e1/0099/24  ",
    "Telefon": "3,8165E+11",
    "Email": "jasmina.matic@gmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 17,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 89,
    "Ime": "ANDREJA",
    "Prezime": "SOLAROV  ",
    "DatumRodjenja": "1.12.2002",
    "BrojIndeksa": "1m1/0065/23  ",
    "Telefon": "3,81657E+11",
    "Email": "andreja.solarov@hotmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 45,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 1
  },
  {
    "StudentId": 90,
    "Ime": "DRAGAN",
    "Prezime": "BRKIĆ  ",
    "DatumRodjenja": "1.12.2005",
    "BrojIndeksa": "2p1/0171/22  ",
    "Telefon": "3,81602E+11",
    "Email": "dragan.brkic@yahoo.com  ",
    "Ulica": "TOPLIČKA",
    "BrojKuce": 26,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 91,
    "Ime": "GORAN",
    "Prezime": "PUŠONJA  ",
    "DatumRodjenja": "1.12.2004",
    "BrojIndeksa": "1i1/0025/24  ",
    "Telefon": "3,81618E+11",
    "Email": "goran.pusonja@gmail.com  ",
    "Ulica": "IGMANSKA",
    "BrojKuce": 16,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 92,
    "Ime": "TATJANA",
    "Prezime": "DILJAK  ",
    "DatumRodjenja": "1.12.2004",
    "BrojIndeksa": "1u1/0052/23  ",
    "Telefon": "3,81624E+11",
    "Email": "tatjana.diljak@hotmail.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 45,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 93,
    "Ime": "ANA",
    "Prezime": "GAŠI  ",
    "DatumRodjenja": "1.12.2005",
    "BrojIndeksa": "2m1/0112/24  ",
    "Telefon": "3,81636E+11",
    "Email": "ana.gasi@gmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 38,
    "PTT": 11460,
    "Grad": "Barajevo",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 94,
    "Ime": "EVICA",
    "Prezime": "ĐORĐEVIĆ  ",
    "DatumRodjenja": "2.1.2003",
    "BrojIndeksa": "2e1/0030/22  ",
    "Telefon": "3,81648E+11",
    "Email": "evica.djordjevic@yahoo.com  ",
    "Ulica": "SLAVUJEV VENAC",
    "BrojKuce": 24,
    "PTT": 11080,
    "Grad": "Zemun",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 95,
    "Ime": "MIRA",
    "Prezime": "DAVIDOVIĆ  ",
    "DatumRodjenja": "2.1.2005",
    "BrojIndeksa": "1p1/0127/23  ",
    "Telefon": "3,81655E+11",
    "Email": "mira.davidovic@gmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 31,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 96,
    "Ime": "STANISAV",
    "Prezime": "KOSANOVIĆ  ",
    "DatumRodjenja": "2.1.2002",
    "BrojIndeksa": "2u1/0070/24  ",
    "Telefon": "3,81604E+11",
    "Email": "stanisav.kosanovic@hotmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 38,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 1
  },
  {
    "StudentId": 97,
    "Ime": "NEBOJŠA",
    "Prezime": "MARJANOVIĆ  ",
    "DatumRodjenja": "2.1.2005",
    "BrojIndeksa": "2i1/0170/23  ",
    "Telefon": "3,81616E+11",
    "Email": "nebojsa.marjanovic@gmail.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 9,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 1
  },
  {
    "StudentId": 98,
    "Ime": "RAJKO",
    "Prezime": "RISTOVIĆ  ",
    "DatumRodjenja": "2.1.2005",
    "BrojIndeksa": "1e1/0086/22  ",
    "Telefon": "3,81621E+11",
    "Email": "rajko.ristovic@yahoo.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 49,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 1
  },
  {
    "StudentId": 99,
    "Ime": "SRĐAN",
    "Prezime": "PALIBRK  ",
    "DatumRodjenja": "2.1.2001",
    "BrojIndeksa": "2m1/0026/24  ",
    "Telefon": "3,8164E+11",
    "Email": "srdjan.palibrk@gmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 18,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 1
  },
  {
    "StudentId": 100,
    "Ime": "MARINA",
    "Prezime": "SMILJANIĆ  ",
    "DatumRodjenja": "2.1.2005",
    "BrojIndeksa": "1i1/0181/23  ",
    "Telefon": "3,81643E+11",
    "Email": "marina.smiljanic@hotmail.com  ",
    "Ulica": "RTANJSKA",
    "BrojKuce": 7,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 101,
    "Ime": "MIROSLAV",
    "Prezime": "TOMANOVIĆ  ",
    "DatumRodjenja": "2.1.2005",
    "BrojIndeksa": "2p1/0098/22  ",
    "Telefon": "3,81657E+11",
    "Email": "miroslav.tomanovic@yahoo.com  ",
    "Ulica": "DIMITRIJA TUCOVIĆA",
    "BrojKuce": 39,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 1
  },
  {
    "StudentId": 102,
    "Ime": "MAREA",
    "Prezime": "JOKIĆ  ",
    "DatumRodjenja": "2.1.2002",
    "BrojIndeksa": "2e1/0102/24  ",
    "Telefon": "3,81608E+11",
    "Email": "marea.jokic@gmail.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 34,
    "PTT": 11060,
    "Grad": "Palilula",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 103,
    "Ime": "VLADANA",
    "Prezime": "ĐURĐEVIĆ  ",
    "DatumRodjenja": "2.2.2003",
    "BrojIndeksa": "1u1/0175/23  ",
    "Telefon": "3,81619E+11",
    "Email": "vladana.djordjevic@hotmail.com  ",
    "Ulica": "SLAVUJEV VENAC",
    "BrojKuce": 14,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 2
  },
  {
    "StudentId": 104,
    "Ime": "MARIJA",
    "Prezime": "ŠARIĆ  ",
    "DatumRodjenja": "2.2.2002",
    "BrojIndeksa": "1m1/0134/22  ",
    "Telefon": "3,81621E+11",
    "Email": "marija.saric@yahoo.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 43,
    "PTT": 11000,
    "Grad": "Stari Grad",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 2
  },
  {
    "StudentId": 105,
    "Ime": "VESNA",
    "Prezime": "UROŠEVIĆ  ",
    "DatumRodjenja": "2.2.2005",
    "BrojIndeksa": "2i1/0016/24  ",
    "Telefon": "3,81637E+11",
    "Email": "vesna.urosevic@gmail.com  ",
    "Ulica": "KOSTE TAUŠANOVIĆA",
    "BrojKuce": 8,
    "PTT": 11060,
    "Grad": "Palilula",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  },
  {
    "StudentId": 106,
    "Ime": "SNEŽANA",
    "Prezime": "JOVANOVIĆ  ",
    "DatumRodjenja": "2.2.2003",
    "BrojIndeksa": "1e1/0042/23  ",
    "Telefon": "3,81642E+11",
    "Email": "snezana.jovanovic@hotmail.com  ",
    "Ulica": "TOPLIČKA",
    "BrojKuce": 22,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 3,
    "PolId": 2
  },
  {
    "StudentId": 107,
    "Ime": "MIROLJUB",
    "Prezime": "KNEŽEVIĆ  ",
    "DatumRodjenja": "2.2.2005",
    "BrojIndeksa": "2u1/0124/22  ",
    "Telefon": "3,81655E+11",
    "Email": "miroljub.knezevic@gmail.com  ",
    "Ulica": "SLAVUJEV VENAC",
    "BrojKuce": 12,
    "PTT": 11050,
    "Grad": "Zvezdara",
    "Zemlja": "Srbija",
    "SmerId": 2,
    "PolId": 1
  },
  {
    "StudentId": 108,
    "Ime": "SANJA",
    "Prezime": "VOJNOVIĆ  ",
    "DatumRodjenja": "2.2.2003",
    "BrojIndeksa": "1p1/0139/24  ",
    "Telefon": "3,81607E+11",
    "Email": "sanja.vojnovic@yahoo.com  ",
    "Ulica": "BRAĆE RIBNIKAR",
    "BrojKuce": 17,
    "PTT": 11010,
    "Grad": "Voždovac",
    "Zemlja": "Srbija",
    "SmerId": 4,
    "PolId": 2
  },
  {
    "StudentId": 109,
    "Ime": "VLADIMIR",
    "Prezime": "VASIĆ  ",
    "DatumRodjenja": "2.2.2003",
    "BrojIndeksa": "2m1/0035/23  ",
    "Telefon": "3,81612E+11",
    "Email": "vladimir.vasic@hotmail.com  ",
    "Ulica": "STANKA VRAZA",
    "BrojKuce": 6,
    "PTT": 11000,
    "Grad": "Savski Venac",
    "Zemlja": "Srbija",
    "SmerId": 5,
    "PolId": 1
  },
  {
    "StudentId": 110,
    "Ime": "IVANA",
    "Prezime": "MILENKOVIĆ",
    "DatumRodjenja": "2.2.2003",
    "BrojIndeksa": "2i1/0038/24",
    "Telefon": "3,81622E+11",
    "Email": "ivana.milenkovic@gmail.com  ",
    "Ulica": "STJEPANA LJUBIŠE",
    "BrojKuce": 4,
    "PTT": 11500,
    "Grad": "Obrenovac",
    "Zemlja": "Srbija",
    "SmerId": 1,
    "PolId": 2
  }
]

export default Studenti;